# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Drink title', max_length=255, unique=True)),
                ('sorder', models.IntegerField(help_text='Sorting order in the drop-down lists')),
            ],
            options={
                'verbose_name': 'drink',
                'verbose_name_plural': 'drinks',
                'ordering': ['sorder'],
            },
        ),
    ]
